### ISSUE TITLE
Ability to open in a vertical split

### ISSUE THREAD

**Issue by kevintraver** [brettanomyces/nvim-terminus#13]
Would be nice to have an easy way to open in a vertical split. Maybe something like `VTerminusOpen`.

**Comment by kevintraver** [comment]
Maybe this doesn't necessarily need to be included... I could do something like this: 
https://github.com/vimlab/split-term.vim/blob/master/plugin/split-term.vim

Just a thought

**Comment by brettanomyces** [comment]
```
:vsplit +TerminusOpen
```

I have the following mappings in my `$MYVIMRC`

```
" open new terminal buffer in horizontal split
tnoremap <leader>" <c-\><c-n>:below split +TerminusOpen<cr>
nnoremap <leader>" :below split +TerminusOpen<cr>

" open new terminal buffer in vertical split
tnoremap <leader>% <c-\><c-n>:vertical rightbelow split +TerminusOpen<cr>
nnoremap <leader>% :vertical rightbelow split +TerminusOpen<cr>
```

**Comment by kevintraver** [comment]
Awesome. Thanks!
