### ISSUE TITLE
Clipboard gets wiped after opening scratch buffer

### ISSUE THREAD

**Issue by tpict** [brettanomyces/nvim-terminus#9]
A little annoyance - on Ubuntu with `set clipboard=unnamedplus`, the contents of my default register gets wiped when loading the scratch buffer

**Comment by brettanomyces** [comment]
Sorry for taking so long to reply but thanks for raising the issue! I'm pretty busy at the moment but I'll look into it when I get a chance.

**Comment by tpict** [comment]
Thank you very much!
